server:
  port: 8003

vod:
  ak: LTAI5tDoiUV5w9kMMqovxXUh
  sk: KNryDnaTbyrPq8ljeXSsc3v93UwZec
  endPoint: cn-shenzhen

spring:
  application:
    name: cloud-service-vod

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  cloud:
    nacos:
      discovery:
        server-addr: 124.71.71.18:8848



