server:
  port: 8002

spring:
  application:
    name: cloud-service-obs

  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: 124.71.71.18:8848


huawei:
  obs:
    ak: LTAI5tDoiUV5w9kMMqovxXUh
    sk: KNryDnaTbyrPq8ljeXSsc3v93UwZec
    endPoint: oss-cn-shenzhen.aliyuncs.com
    bucketName: cloud-teacher-avatar
